---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: false

platforms:
  - name: debian-7-chef
    driver:
      box: debian-7-chef
      box_url: http://bit.ly/1weDdiJ
      network:
        - ['private_network', {ip: '172.28.128.3'}]

provisioner:
  name: chef_solo

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    #encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[chef-authldap::default]
    attributes:
      chef-authldap:
        nss_admin: 'cn=nss_user,dc=example,dc=com'
        nss_password: 'password'
        base_dn: 'dc=example,dc=com'
        base_host: 'ldap://ldap.example.com'
        home_path: '/home'
