name 'chef-authldap'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures chef-authldap'
long_description 'Installs/Configures chef-authldap'
version '0.1.0'
